In [1]:
!pip install openpyxl scipy

Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (1.16.3)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)
Requirement already satisfied: numpy<2.6,>=1.25.2 in /usr/local/lib/python3.12/dist-packages (from scipy) (2.0.2)

In [2]:
import pandas as pd
import numpy as np
from scipy.stats import ttest_ind

In [3]:
from google.colab import files

uploaded = files.upload()

Saving Cleaned_Sales_Dataset.xlsx to Cleaned_Sales_Dataset.xlsx

In [4]:
df = pd.read_excel("Cleaned_Sales_Dataset.xlsx")

In [5]:
df.head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales,Month
0,ORD100002,2025-02-25,CUST5529,Customer_227,30,Female,Bengaluru,Rice,Grocery,7,2829.77,19808.39,February
1,ORD100003,2025-10-14,CUST3127,Customer_182,63,Male,Bengaluru,Book,Education,5,27906.16,139530.80,October
2,ORD100004,2025-05-13,CUST8887,Customer_487,62,Female,Bengaluru,Book,Education,8,37491.06,299928.48,May
3,ORD100005,2025-12-02,CUST2515,Customer_470,65,Female,Kolkata,Mobile,Electronics,9,28541.36,256872.24,December
4,ORD100006,2025-11-20,CUST4796,Customer_380,44,Male,Bengaluru,Rice,Grocery,10,14036.59,140365.90,November

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       1000 non-null   object
 1   Order_Date     1000 non-null   datetime64[ns]
 2   Customer_ID    1000 non-null   object
 3   Customer_Name  1000 non-null   object
 4   Age            1000 non-null   int64
 5   Gender         1000 non-null   object
 6   City           1000 non-null   object
 7   Product        1000 non-null   object
 8   Category       1000 non-null   object
 9   Quantity       1000 non-null   int64
 10  Unit_Price     1000 non-null   float64
 11  Total_Sales    1000 non-null   float64
 12  Month          1000 non-null   object
dtypes: datetime64[ns](1), float64(2), int64(2), object(8)
memory usage: 101.7+ KB

In [7]:
df.describe()

,Order_Date,Age,Quantity,Unit_Price,Total_Sales
count,1000,1000.000000,1000.000000,1000.000000,1000.000000
mean,2025-07-03 11:19:40.800000,41.353000,5.435000,25486.783410,139399.439650
min,2025-01-01 00:00:00,18.000000,1.000000,145.780000,437.340000
25%,2025-03-30 18:00:00,30.000000,3.000000,13895.722500,47066.632500
50%,2025-07-01 00:00:00,41.000000,5.000000,25398.740000,108594.025000
75%,2025-10-07 06:00:00,53.000000,8.000000,37512.382500,203722.882500
max,2026-01-01 00:00:00,65.000000,10.000000,49997.530000,493677.500000
std,NaN,13.683626,2.838632,14179.402361,114100.051546

In [8]:
print(df["Category"].unique())

['Grocery' 'Education' 'Electronics' 'Fashion' 'Furniture']

In [9]:
electronics = df[df["Category"]=="Electronics"]["Total_Sales"]

grocery = df[df["Category"]=="Grocery"]["Total_Sales"]

In [10]:
print("Electronics:", len(electronics))
print("Grocery:", len(grocery))

Electronics: 354
Grocery: 153

In [11]:
t_stat, p_value = ttest_ind(electronics, grocery)

print("T-statistic =", t_stat)
print("P-value =", p_value)

T-statistic = -0.16485689689626543
P-value = 0.8691225868984803

In [12]:
alpha = 0.05

if p_value < alpha:
    print("Reject the Null Hypothesis")
    print("There is a statistically significant difference between Electronics and Grocery sales.")
else:
    print("Fail to Reject the Null Hypothesis")
    print("There is NO statistically significant difference between Electronics and Grocery sales.")

Fail to Reject the Null Hypothesis
There is NO statistically significant difference between Electronics and Grocery sales.

In [13]:
print("Average Electronics Sales:", electronics.mean())
print("Average Grocery Sales:", grocery.mean())

Average Electronics Sales: 143442.32118644068
Average Grocery Sales: 145305.30248366014

In [14]:
print("Electronics Standard Deviation:", electronics.std())
print("Grocery Standard Deviation:", grocery.std())

Electronics Standard Deviation: 117601.7926058285
Grocery Standard Deviation: 114918.08600790391

**Final Summary**

In [15]:
print("========== HYPOTHESIS TESTING SUMMARY ==========")

print("\nNull Hypothesis (H0):")
print("There is no significant difference in average sales between Electronics and Grocery.")

print("\nAlternative Hypothesis (H1):")
print("There is a significant difference in average sales between Electronics and Grocery.")

print("\nAverage Electronics Sales:", electronics.mean())
print("Average Grocery Sales:", grocery.mean())

print("\nT-statistic:", t_stat)
print("P-value:", p_value)

if p_value < 0.05:
    print("\nConclusion:")
    print("Reject H0.")
    print("Electronics and Grocery sales are significantly different.")
else:
    print("\nConclusion:")
    print("Fail to Reject H0.")
    print("No statistically significant difference was found.")

========== HYPOTHESIS TESTING SUMMARY ==========

Null Hypothesis (H0):
There is no significant difference in average sales between Electronics and Grocery.

Alternative Hypothesis (H1):
There is a significant difference in average sales between Electronics and Grocery.

Average Electronics Sales: 143442.32118644068
Average Grocery Sales: 145305.30248366014

T-statistic: -0.16485689689626543
P-value: 0.8691225868984803

Conclusion:
Fail to Reject H0.
No statistically significant difference was found.